---
db:
  host: "db"
  user: "postgres"
  password: "sprinkler"
  dbname: "postgres"
  sslmode: "disable"

orchard:
  address: ":8082"

control:
  address: ":8080"
  trustedProxies:
    - "0.0.0.0/0"
    - "::/0"
  # leave empty to read from environment variable API_KEY_ENABLED
  apiKeyEnabled: 
  # leave empty to read from environment variable XFCC_ENABLED
  xfccEnabled: 
  # echo -n changeme | shasum -a 256 | awk '{print $1}'
  apiKey: "057ba03d6c44104863dc7361fe4578965d1887360f90a0895882e58a6248fc86"
  xfccHeaderName: "x-forwarded-client-cert"
  xfccMustContain: "changeme"

scheduler:
  interval: "1s"
  orchard:
    address: "http://ws:8082"
    # apiKeyName: "x-api-key"
    # apiKey: "changeme"

cleanup:
  scheduledWorkflow: "720h"
  workflowActivationLock: "1h"
  workflowSchedulerLock: "1h"

# configs for static credentials or role arn to assume
# aws:
#   clientRegion: "changeme"
#   staticCredentials:
#     awsAccessKeyId: "changeme"
#     awsSecretKey: "changeme"
#     sessionToken: "changeme"
#   assumeRoleArn: "changeme"
...
